name: Linter for bash

# Controls when the action will run.
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC2059 -e SC2034 -e SC1090
      with:
        scandir: './scripts/bash'
        ignore_paths: ignoreme ignoremetoo
        ignore_names: ignorable.sh
        severity: warning
        version: v0.7.0
